support --context tar://stdin

diff --git a/kubectl-kaniko b/kubectl-kaniko
--- a/kubectl-kaniko
+++ b/kubectl-kaniko
@@ -39,10 +39,12 @@ while [ $# -gt 0 ]; do
   esac
 done
 
-if [ -n "$context" ]; then
+if [ -z "$context" ]; then
+  args+="\"--context=\" ]"
+elif [ -d "$context" ]; then
   args+="\"--context=tar://stdin\" ]"
 else
-  args="$(echo "$args" | awk '1' RS=', \n') ]"
+  args+="\"--context=$context\" ]"
 fi
 
 image="gcr.io/kaniko-project/executor:v1.0.0"
@@ -88,6 +90,11 @@ if [ "$m" -lt 18 ]; then
   generator="--generator=run-pod/v1"
 fi
 
+if [ -n "$context" ] && ( [ ! -d "$context" ] && [ "$context" != "tar://stdin" ] ); then
+  echo "Error: $context: Cannot open: Not a directory" >&2
+  exit 1
+fi
+
 trap "kubectl delete "secret/$name" "pod/$name" --wait=false $kubecontext $kubeconfig $namespace 2>/dev/null" EXIT
 
 if [ -f ~/.docker/config.json ]; then
@@ -95,7 +102,7 @@ if [ -f ~/.docker/config.json ]; then
 fi
 
 echo "spawning \"$name\""
-if [ -n "$context" ]; then
+if [ -n "$context" ] && [ "$context" != "tar://stdin" ]; then
   tar --record-size=1M --checkpoint=1 --checkpoint-action='ttyout=Sending build context to Kaniko %{r}T\r' -C "$context" -czf - . | \
     kubectl run --image "$image" --restart=Never --overrides="$overrides" -i "$name" $generator $kubecontext $kubeconfig $namespace
 else
